config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books'=> 'books#index'
  get 'books/:id'=> 'books#show', as: 'book'
  get 'books/:id/edit'=> 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update'
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top

  end

  def new

  end


  def create
    @book = Book.new(book_params)
    @books=Book.all

    if @book.save
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book.id)

    else
      flash.now[:danger] = "Book was created failed."
      render  :index


    end

  end



  def index
     @books = Book.all
     @book = Book.new
  end




  def show
     @book = Book.find(params[:id])
  end




  def edit
    @book = Book.find(params[:id])
  end




  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      flash.now[:danger] = "Editing Book"
      render :edit
    end
  end




  def destroy
    @book = Book.find(params[:id])

    @book.destroy
    flash[:success] = "Book was successfully destroyed."
    redirect_to books_path


  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>



<% if @book.errors.any? %>
<p><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</p>
  <% @book.errors.count %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_path(@book.id), method: :patch do |f| %>

<p>Title</p>
 <%= f.text_field :title %>

<p>body</p>
<%= f.text_area :body %>

<div><%= f.submit 'Update Book' %></div>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", '/books' %>

<% end %>

app/views/books/index.html.erb
<p id="notice"></p>
<h1>Books</h1>

<table>
  <div class="thead">
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </div>


<% @books.each do |book| %>
 <tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td> <%= link_to "Show", book_path(book.id) %></td>
  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy", destroy_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
 </tr>

<% end %>

</table>




<h2>New book</h2>


<% if @book.errors.any? %>
<p><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</p>
 <% @book.errors.count %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>


<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Body<p>
  <%= f.text_area :body %>

  <div>
    <%= f.submit 'Create Book' %>
  </div>

<% end %>

app/views/books/show.html.erb
<h6>Title:</h6>
<p><%= @book.title %></p>

<h6>Body:</h6>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", '/books' %>

app/views/books/top.html.erb
<h1>ようこそ
 <b>Bookers</b>
 へ！
</h1>

<p>
  <b>Bookers</b>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p>印象を共有し交換することができます</p>

<a><%= link_to "start", '/books' %> </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>

    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>